spring:
  application:
    name: admin
  boot:
    admin:
      discovery:
        enabled: true  

server:
  port: 9090          # Puerto donde se verá la consola de Admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
