server:
  port: 8080   # O el puerto que uses para el Gateway

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1

            - id: cart-service
              uri: lb://cart
              predicates:
                - Path=/cart/**
              filters:
                - StripPrefix=1

            - id: invoice-service
              uri: lb://invoice
              predicates:
                - Path=/invoice/**
              filters:
                - StripPrefix=1

            - id: auth-service
              uri: lb://servicio-autenticacion
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true